---
# tasks/files.yml

- name: ocStore | Restore | Sync files
  shell: "rsync -amq {{ tmp_dir.path }}/{{ ocstore_backup_files_dir }}/{{ item.path | basename }}/ {{ item.path }}"
  with_items: "{{ ocstore_backup_from }}"
  become: yes
